---

- name: Install percona repo.
  yum:
    name: "{{ percona_repo_url }}"
    state: present

- name: Import percona GPG key.
  rpm_key:
    key: "{{ percona_repo_gpg_key_url }}"
    state: present
